http:
  listener:
    host: "0.0.0.0"
    port: "9082"
    path: "/fastgo/{serviceType}"
    
sql:
  host: "sql12.freesqldatabase.com"
  port: "3306"
  user: "sql12597378"
  pass: "dyMNcGRjBu"
  db: "sql12597378"